name: toolbox_app
description: Caja de herramientas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: any
  dio: any
  just_audio: any
  qr_flutter: any
  url_launcher: any

dev_dependencies:
  flutter_native_splash: any
  flutter_launcher_icons: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
flutter_native_splash:
  color: "#02040A"
  image: assets/images/fulltoolbox.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#02040A"
    image: assets/images/fulltoolbox.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/elvis.png
  adaptive_icon_background: "#02040A"
  adaptive_icon_foreground: assets/images/elvis.png